apiVersion: v1
kind: Service
metadata:
  name: vprodb
  namespace: devops-project
spec:
  selector:
    app: vprodb
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: vprodb-port
      protocol: TCP