apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp
spec:
  replicas: 1   # HPA will control replicas
  selector:
    matchLabels:
      app: vproapp
  template:
    metadata:
      labels:
        app: vproapp
    spec:
      initContainers:
        - name: check-vprodb
          image: busybox
          command: ['sh', '-c', 'until nc -zv vprodb 3306; do sleep 2; done']
        - name: check-vprocache01
          image: busybox
          command: ['sh', '-c', 'until nc -zv vprocache01 11211; do sleep 2; done']
        - name: check-vpromq01
          image: busybox
          command: ['sh', '-c', 'until nc -zv vpromq01 5672; do sleep 2; done']

      containers:
        - name: vproapp
          image: sansv/tomcat-app-image:v1
          ports:
            - name: vproapp-port
              containerPort: 8080

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
