apiVersion: v1
kind: Service
metadata:
  name: vproapp
  namespace: devops-project
spec:
  selector:
    app: vproapp
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: vproapp-port
      protocol: TCP