apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp
  namespace: devops-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vproapp
  template:
    metadata:
      labels:
        app: vproapp
    spec:
      terminationGracePeriodSeconds: 60

      initContainers:
        - name: check-vprodb
          image: busybox
          command: ['sh', '-c', 'until nc -zv vprodb 3306; do sleep 2; done']
        - name: check-vprocache01
          image: busybox
          command: ['sh', '-c', 'until nc -zv vprocache01 11211; do sleep 2; done']
        - name: check-vpromq01
          image: busybox
          command: ['sh', '-c', 'until nc -zv vprormq01 5672; do sleep 2; done']

      containers:
        - name: vproapp
          image: sansv/tomcat-app-image:v1
          ports:
            - name: vproapp-port
              containerPort: 8080

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

          readinessProbe:
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 180
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 5
