apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vpro-ingress
  namespace: prod
spec:
  ingressClassName: nginx
  rules:
  - host: reva.sandysanj.site
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vproapp
            port:
              number: 8080
