apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vpro-ingress
  namespace: devops-project
  labels:
    name: vpro-ingress

spec:
  ingressClassName: nginx  # Specifies that this Ingress should be handled by the NGINX Ingress Controller
  rules:
    - host: k8s.practicesandy.xyz
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: vproapp  # Ensure this matches the actual Service name
                port:
                  number: 8080
