apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vprormq
  namespace: prod
spec:
  serviceName: vprormq
  replicas: 1
  selector:
    matchLabels:
      app: vprormq
  template:
    metadata:
      labels:
        app: vprormq
    spec:
      containers:
      - name: rabbitmq
        image: sansv/rmq-webapp-project
        ports:
        - containerPort: 5672
        env:
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: rmq-pass
        - name: RABBITMQ_DEFAULT_USER
          value: guest
