apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproarmq01
  namespace: devops-project
  labels:
    app: vproarmq01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vproarmq01
  template:
    metadata:
      labels:
        app: vproarmq01
    spec:
      containers:
        - name: vproarmq
          image: sansv/rmq-webapp-project
          ports:
            - name: vproarmq-port
              containerPort: 5672  # RabbitMQ AMQP port
          env:
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: rmq-pass
            - name: RABBITMQ_DEFAULT_USER
              value: "test"

