apiVersion: v1
kind: Service
metadata:
  name: vpromq01
  namespace: devops-project
spec:
  selector:
    app: vproarmq01
  type: ClusterIP
  ports:
    - port: 5672
      targetPort: vproarmq-port
      protocol: TCP
