apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpromc
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpromc
  template:
    metadata:
      labels:
        app: vpromc
    spec:
      containers:
      - name: memcached
        image: sansv/mc-webapp-project
        ports:
        - containerPort: 11211

        livenessProbe:
          tcpSocket:
            port: 11211
          initialDelaySeconds: 20

        readinessProbe:
          tcpSocket:
            port: 11211
          initialDelaySeconds: 5
